name: Databricks Deployment

on:
  workflow_dispatch:
    inputs:
      batch_date:
        description: 'The batch date'
        required: true
        default: '2024-04-28'
      table:
        description: 'The table name'
        required: true
        default: 'example_table'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: 10.139.0.4
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch Cluster ID
      id: cluster-id
      run: |
        cluster_id=$(curl -X GET -H "Authorization: Bearer $DATABRICKS_TOKEN" \
          -H "Content-Type: application/json" \
          https://$DATABRICKS_HOST/api/2.0/clusters/list | jq -r '.clusters[] | select(.cluster_name == "Sreenivasulu kattubadi's Personal Compute Cluster") | .cluster_id')
        echo "::set-output name=cluster_id::$cluster_id"

    - name: Run Python script on Databricks
      run: |
        # Authenticate with Databricks API
        curl -X POST -H "Authorization: Bearer $DATABRICKS_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"cluster_id\": \"${{ steps.cluster-id.outputs.cluster_id }}\", \"libraries\": [], \"notebook_task\": {\"notebook_path\": \"/Workspace/Users/etlbigdataautomation@gmail.com/hello\", \"base_parameters\": {\"batch_date\": \"${{ github.event.inputs.batch_date }}\", \"table\": \"${{ github.event.inputs.table }}\"}}}" \
          https://$DATABRICKS_HOST/api/2.0/jobs/runs/submit

      env:
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
