name: Manual Python Deployment

on:
  workflow_dispatch:
    inputs:
      batch_date:
        description: 'The batch date'
        required: true
        default: '2024-04-28'
      table:
        description: 'The table name'
        required: true
        default: 'example_table'

jobs:
  build:
    runs-on: ubuntu-latest

#    env:
#      BATCH_DATE: ${{ github.event.inputs.batch_date }}
#      TABLE: ${{ github.event.inputs.table }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      run: python main2.py
